name: flutter_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Utility dependencies
  http: ^1.4.0
  logger: ^2.6.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  
  # Icons  
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Product specific
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
 
  lottie: ^3.3.1
  connectivity_plus: ^6.1.4
 
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^7.1.1
<<<<<<< HEAD
  shimmer: ^3.0.0
=======
  image_picker: ^1.1.2
  cloudinary: ^1.2.0
  cloudinary_sdk: ^5.0.0+1
  cached_network_image: ^3.4.1
>>>>>>> 4d9ffbbc9c17fd6ba605274173703c24dcad8fd7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/
    - assets/images/user/
