name: flutter_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Utility dependencies
  http: ^1.4.0
  logger: ^2.6.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1

  # Icons  
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State management
  get: ^4.7.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
