// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeJYEtN5A7XNQp-5_RkolsBrqBKNSNMOQ',
    appId: '1:427159389841:web:e270720740d97e95fda130',
    messagingSenderId: '427159389841',
    projectId: 'ecommerceapp-6df02',
    authDomain: 'ecommerceapp-6df02.firebaseapp.com',
    storageBucket: 'ecommerceapp-6df02.firebasestorage.app',
    measurementId: 'G-H15L013SP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJK8y33OGSFBI_McyptTBxIf1R3VgSAiQ',
    appId: '1:427159389841:android:fce54a994c50c719fda130',
    messagingSenderId: '427159389841',
    projectId: 'ecommerceapp-6df02',
    storageBucket: 'ecommerceapp-6df02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZyO8JA4UMw-Ynfk-LGIJFIQfga36cO4',
    appId: '1:427159389841:ios:b71edb8c96d35593fda130',
    messagingSenderId: '427159389841',
    projectId: 'ecommerceapp-6df02',
    storageBucket: 'ecommerceapp-6df02.firebasestorage.app',
    androidClientId: '427159389841-46hn4q4mb5mp4gsqa26lekhm4rvpns9q.apps.googleusercontent.com',
    iosClientId: '427159389841-8iresh0p8g8ci2lc3j1dp139tffu3p3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHZyO8JA4UMw-Ynfk-LGIJFIQfga36cO4',
    appId: '1:427159389841:ios:b71edb8c96d35593fda130',
    messagingSenderId: '427159389841',
    projectId: 'ecommerceapp-6df02',
    storageBucket: 'ecommerceapp-6df02.firebasestorage.app',
    androidClientId: '427159389841-46hn4q4mb5mp4gsqa26lekhm4rvpns9q.apps.googleusercontent.com',
    iosClientId: '427159389841-8iresh0p8g8ci2lc3j1dp139tffu3p3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeJYEtN5A7XNQp-5_RkolsBrqBKNSNMOQ',
    appId: '1:427159389841:web:c9b528c8f59fde7ffda130',
    messagingSenderId: '427159389841',
    projectId: 'ecommerceapp-6df02',
    authDomain: 'ecommerceapp-6df02.firebaseapp.com',
    storageBucket: 'ecommerceapp-6df02.firebasestorage.app',
    measurementId: 'G-XRW1TRHWMK',
  );

}